development: &development
  adapter: postgresql
  encoding: unicode
  database: fiveminuteruby_development
  pool: 5
  username: austin_schneider
  password: 

test: &test
  <<: *development
  database: fiveminuteruby_test

cucumber:
  <<: *test