development:
  adapter: postgresql
  encoding: unicode
  database: fiveminuteruby_development
  pool: 5
  username: austin_schneider
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: fiveminuteruby_test
  pool: 5
  username: austin_schneider
  password: 